/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics/breakdown/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Breakdown By Category */
        get: operations["breakdown_by_category_api_analytics_breakdown_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/breakdown/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Breakdown By Priority */
        get: operations["breakdown_by_priority_api_analytics_breakdown_priority_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/breakdown/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Breakdown By Team */
        get: operations["breakdown_by_team_api_analytics_breakdown_team_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/owner-pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner Pending */
        get: operations["owner_pending_api_analytics_owner_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_categories__category_id__patch"];
        trace?: never;
    };
    "/api/custom-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Custom Fields */
        get: operations["list_custom_fields_api_custom_fields_get"];
        put?: never;
        /** Create Custom Field */
        post: operations["create_custom_field_api_custom_fields_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Custom Field */
        patch: operations["update_custom_field_api_custom_fields__field_id__patch"];
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_api_roles_get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_api_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_api_roles__role_id__patch"];
        trace?: never;
    };
    "/api/sla-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sla Settings */
        get: operations["get_sla_settings_api_sla_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Sla Settings */
        patch: operations["update_sla_settings_api_sla_settings_patch"];
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Tag */
        patch: operations["update_tag_api_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_api_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Team */
        patch: operations["rename_team_api_teams__team_id__patch"];
        trace?: never;
    };
    "/api/teams/{team_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Detail */
        get: operations["get_team_detail_api_teams__team_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["add_member_api_teams__team_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_teams__team_id__members__member_id__delete"];
        options?: never;
        head?: never;
        /** Update Member Role */
        patch: operations["update_member_role_api_teams__team_id__members__member_id__patch"];
        trace?: never;
    };
    "/api/teams/{team_id}/set-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Default Team */
        post: operations["set_default_team_api_teams__team_id__set_default_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_tickets_get"];
        put?: never;
        /**
         * Create Ticket
         * @description Workflow A (spec section 5): dashboard creates the ticket, then
         *     pushes it to Slack unless the caller explicitly opts out.
         */
        post: operations["create_ticket_api_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_api_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Ticket */
        post: operations["assign_ticket_api_tickets__ticket_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Ticket Priority */
        post: operations["change_ticket_priority_api_tickets__ticket_id__priority_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Ticket */
        post: operations["resolve_ticket_api_tickets__ticket_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Ticket Status */
        post: operations["change_ticket_status_api_tickets__ticket_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Ticket Tags */
        post: operations["update_ticket_tags_api_tickets__ticket_id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Ticket Team */
        post: operations["change_ticket_team_api_tickets__ticket_id__team_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket Timeline */
        get: operations["get_ticket_timeline_api_tickets__ticket_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Slack Events
         * @description Single HTTP entry point for Slack Events API, interactivity
         *     (buttons/modals), and slash commands — Slack Bolt dispatches internally
         *     based on the payload shape. Signature verification happens inside
         *     `_handler.handle` via the app's signing secret.
         */
        post: operations["slack_events_slack_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddTeamMemberRequest */
        AddTeamMemberRequest: {
            /** Role Id */
            role_id: number;
            /** User Id */
            user_id: number;
        };
        /** AssignRequest */
        AssignRequest: {
            /** Owner Id */
            owner_id: number | null;
        };
        /** BreakdownItem */
        BreakdownItem: {
            /** Avg Resolution Hours */
            avg_resolution_hours: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Pending */
            pending: number;
            /** Sla Breached */
            sla_breached: number;
            /** Total */
            total: number;
        };
        /** CategoryCreateRequest */
        CategoryCreateRequest: {
            /** Name */
            name: string;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /**
             * Is Archived
             * @default false
             */
            is_archived: boolean;
            /** Name */
            name: string;
        };
        /** CategoryUpdateRequest */
        CategoryUpdateRequest: {
            /** Is Archived */
            is_archived?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** CustomFieldDefinitionCreateRequest */
        CustomFieldDefinitionCreateRequest: {
            field_type: components["schemas"]["CustomFieldType"];
            /** Label */
            label: string;
            /** Options */
            options?: string[] | null;
        };
        /** CustomFieldDefinitionOut */
        CustomFieldDefinitionOut: {
            field_type: components["schemas"]["CustomFieldType"];
            /** Id */
            id: number;
            /** Is Archived */
            is_archived: boolean;
            /** Label */
            label: string;
            /** Options */
            options: string[] | null;
        };
        /** CustomFieldDefinitionUpdateRequest */
        CustomFieldDefinitionUpdateRequest: {
            /** Is Archived */
            is_archived?: boolean | null;
            /** Label */
            label?: string | null;
            /** Options */
            options?: string[] | null;
        };
        /**
         * CustomFieldType
         * @enum {string}
         */
        CustomFieldType: "text" | "dropdown";
        /** CustomFieldValueInput */
        CustomFieldValueInput: {
            /** Field Definition Id */
            field_definition_id: number;
            /** Value */
            value: string;
        };
        /** CustomFieldValueOut */
        CustomFieldValueOut: {
            /** Field Definition Id */
            field_definition_id: number;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Avg First Response Hours */
            avg_first_response_hours: number | null;
            /** Avg Resolution Hours */
            avg_resolution_hours: number | null;
            created_comparison: components["schemas"]["PeriodComparison"];
            resolved_comparison: components["schemas"]["PeriodComparison"];
            sla_breach_comparison: components["schemas"]["PeriodComparison"];
            /** Sla Breached Last Week */
            sla_breached_last_week: number;
            /** Sla Breached This Week */
            sla_breached_this_week: number;
            /** Sla Breached Tickets */
            sla_breached_tickets: number;
            /** Sla Compliance Pct */
            sla_compliance_pct: number | null;
            /** Tickets Created Last Week */
            tickets_created_last_week: number;
            /** Tickets Created This Week */
            tickets_created_this_week: number;
            /** Tickets Pending */
            tickets_pending: number;
            /** Tickets Resolved Last Week */
            tickets_resolved_last_week: number;
            /** Tickets Resolved This Week */
            tickets_resolved_this_week: number;
            /** Total Open Tickets */
            total_open_tickets: number;
            /** Total Resolved Tickets */
            total_resolved_tickets: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OwnerPendingItem */
        OwnerPendingItem: {
            /** Owner Id */
            owner_id: number | null;
            /** Owner Name */
            owner_name: string;
            /** Pending Count */
            pending_count: number;
        };
        /** PeriodComparison */
        PeriodComparison: {
            /** Change Pct */
            change_pct: number | null;
            /** Current */
            current: number;
            /** Previous */
            previous: number;
        };
        /** PriorityChangeRequest */
        PriorityChangeRequest: {
            priority: components["schemas"]["TicketPriority"];
        };
        /** RoleCreateRequest */
        RoleCreateRequest: {
            /**
             * Can Create Settings
             * @default false
             */
            can_create_settings: boolean;
            /**
             * Can Delete Settings
             * @default false
             */
            can_delete_settings: boolean;
            /**
             * Can Edit Settings
             * @default false
             */
            can_edit_settings: boolean;
            /** Name */
            name: string;
        };
        /** RoleOut */
        RoleOut: {
            /** Can Create Settings */
            can_create_settings: boolean;
            /** Can Delete Settings */
            can_delete_settings: boolean;
            /** Can Edit Settings */
            can_edit_settings: boolean;
            /** Id */
            id: number;
            /** Is Archived */
            is_archived: boolean;
            /** Name */
            name: string;
        };
        /** RoleUpdateRequest */
        RoleUpdateRequest: {
            /** Can Create Settings */
            can_create_settings?: boolean | null;
            /** Can Delete Settings */
            can_delete_settings?: boolean | null;
            /** Can Edit Settings */
            can_edit_settings?: boolean | null;
            /** Is Archived */
            is_archived?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** SLASettingsOut */
        SLASettingsOut: {
            /** Default Hours */
            default_hours: number;
        };
        /** SLASettingsUpdateRequest */
        SLASettingsUpdateRequest: {
            /** Default Hours */
            default_hours: number;
        };
        /** StatusChangeRequest */
        StatusChangeRequest: {
            status: components["schemas"]["TicketStatus"];
        };
        /** TagCreateRequest */
        TagCreateRequest: {
            /** Name */
            name: string;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: number;
            /**
             * Is Archived
             * @default false
             */
            is_archived: boolean;
            /** Name */
            name: string;
        };
        /** TagUpdateRequest */
        TagUpdateRequest: {
            /** Is Archived */
            is_archived?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** TagsUpdateRequest */
        TagsUpdateRequest: {
            /** Tag Ids */
            tag_ids: number[];
        };
        /** TeamChangeRequest */
        TeamChangeRequest: {
            /** Team Id */
            team_id: number;
        };
        /** TeamCreateRequest */
        TeamCreateRequest: {
            /** Name */
            name: string;
        };
        /** TeamDetailOut */
        TeamDetailOut: {
            /** Id */
            id: number;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Members */
            members: components["schemas"]["TeamMemberOut"][];
            /** Name */
            name: string;
        };
        /** TeamMemberOut */
        TeamMemberOut: {
            /** Id */
            id: number;
            role: components["schemas"]["RoleOut"];
            user: components["schemas"]["UserOut"];
        };
        /** TeamOut */
        TeamOut: {
            /** Id */
            id: number;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Name */
            name: string;
        };
        /** TeamUpdateRequest */
        TeamUpdateRequest: {
            /** Name */
            name: string;
        };
        /** TicketCreateRequest */
        TicketCreateRequest: {
            /** Business Id */
            business_id?: string | null;
            /** Category Id */
            category_id: number;
            /**
             * Custom Field Values
             * @default []
             */
            custom_field_values: components["schemas"]["CustomFieldValueInput"][];
            /** Customer */
            customer: string;
            /** Description */
            description: string;
            /** Doctor Name */
            doctor_name?: string | null;
            /** Mobile Number */
            mobile_number?: string | null;
            /** Owner Id */
            owner_id?: number | null;
            /** @default medium */
            priority: components["schemas"]["TicketPriority"];
            /**
             * Push To Slack
             * @default true
             */
            push_to_slack: boolean;
            /** Slack Channel Id */
            slack_channel_id?: string | null;
            /**
             * Tag Ids
             * @default []
             */
            tag_ids: number[];
            /** Team Id */
            team_id: number;
            /** Title */
            title: string;
        };
        /** TicketListItem */
        TicketListItem: {
            /** Age Seconds */
            age_seconds: number;
            /** Business Id */
            business_id: string | null;
            /** Category Name */
            category_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer */
            customer: string;
            /** Doctor Name */
            doctor_name: string | null;
            /** Id */
            id: number;
            /** Mobile Number */
            mobile_number: string | null;
            /** Owner Name */
            owner_name: string | null;
            priority: components["schemas"]["TicketPriority"];
            /** Sla Breached */
            sla_breached: boolean;
            /** Sla Remaining Seconds */
            sla_remaining_seconds: number | null;
            status: components["schemas"]["TicketStatus"];
            /** Team Name */
            team_name: string;
            /** Ticket Number */
            ticket_number: number;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TicketListResponse */
        TicketListResponse: {
            /** Items */
            items: components["schemas"]["TicketListItem"][];
            /** Total */
            total: number;
        };
        /** TicketOut */
        TicketOut: {
            /** Age Seconds */
            age_seconds: number;
            /** Business Id */
            business_id: string | null;
            category: components["schemas"]["CategoryOut"];
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by: components["schemas"]["UserOut"];
            /**
             * Custom Field Values
             * @default []
             */
            custom_field_values: components["schemas"]["CustomFieldValueOut"][];
            /** Customer */
            customer: string;
            /** Description */
            description: string;
            /** Doctor Name */
            doctor_name: string | null;
            /** First Response At */
            first_response_at: string | null;
            /** Id */
            id: number;
            /** Mobile Number */
            mobile_number: string | null;
            owner: components["schemas"]["UserOut"] | null;
            priority: components["schemas"]["TicketPriority"];
            /** Resolved At */
            resolved_at: string | null;
            /** Sla Breached */
            sla_breached: boolean;
            /**
             * Sla Due At
             * Format: date-time
             */
            sla_due_at: string;
            /** Sla Hours */
            sla_hours: number;
            /** Sla Remaining Seconds */
            sla_remaining_seconds: number | null;
            /** Slack Channel Id */
            slack_channel_id: string | null;
            /** Slack Message Ts */
            slack_message_ts: string | null;
            status: components["schemas"]["TicketStatus"];
            support_assignee: components["schemas"]["UserOut"] | null;
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagOut"][];
            team: components["schemas"]["TeamOut"];
            /** Ticket Number */
            ticket_number: number;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TicketPriority
         * @enum {string}
         */
        TicketPriority: "low" | "medium" | "high" | "urgent";
        /**
         * TicketStatus
         * @enum {string}
         */
        TicketStatus: "open" | "in_progress" | "pending" | "resolved" | "closed";
        /** TimelineEvent */
        TimelineEvent: {
            /** Actor Name */
            actor_name: string | null;
            /** Description */
            description: string;
            /** Event Type */
            event_type: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** UpdateTeamMemberRoleRequest */
        UpdateTeamMemberRoleRequest: {
            /** Role Id */
            role_id: number;
        };
        /** UserOut */
        UserOut: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slack User Id */
            slack_user_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    breakdown_by_category_api_analytics_breakdown_category_get: {
        parameters: {
            query?: {
                team_id?: number | null;
                owner_id?: number | null;
                support_assignee_id?: number | null;
                category_id?: number | null;
                priority?: components["schemas"]["TicketPriority"] | null;
                status?: components["schemas"]["TicketStatus"] | null;
                sla_status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breakdown_by_priority_api_analytics_breakdown_priority_get: {
        parameters: {
            query?: {
                team_id?: number | null;
                owner_id?: number | null;
                support_assignee_id?: number | null;
                category_id?: number | null;
                priority?: components["schemas"]["TicketPriority"] | null;
                status?: components["schemas"]["TicketStatus"] | null;
                sla_status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breakdown_by_team_api_analytics_breakdown_team_get: {
        parameters: {
            query?: {
                team_id?: number | null;
                owner_id?: number | null;
                support_assignee_id?: number | null;
                category_id?: number | null;
                priority?: components["schemas"]["TicketPriority"] | null;
                status?: components["schemas"]["TicketStatus"] | null;
                sla_status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    owner_pending_api_analytics_owner_pending_get: {
        parameters: {
            query?: {
                team_id?: number | null;
                owner_id?: number | null;
                support_assignee_id?: number | null;
                category_id?: number | null;
                priority?: components["schemas"]["TicketPriority"] | null;
                status?: components["schemas"]["TicketStatus"] | null;
                sla_status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerPendingItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_analytics_summary_get: {
        parameters: {
            query?: {
                team_id?: number | null;
                owner_id?: number | null;
                support_assignee_id?: number | null;
                category_id?: number | null;
                priority?: components["schemas"]["TicketPriority"] | null;
                status?: components["schemas"]["TicketStatus"] | null;
                sla_status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_custom_fields_api_custom_fields_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomFieldDefinitionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_custom_field_api_custom_fields_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomFieldDefinitionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomFieldDefinitionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_custom_field_api_custom_fields__field_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomFieldDefinitionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomFieldDefinitionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_roles_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_role_api_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sla_settings_api_sla_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLASettingsOut"];
                };
            };
        };
    };
    update_sla_settings_api_sla_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SLASettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLASettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_api_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
        };
    };
    create_team_api_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_team_api_teams__team_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_detail_api_teams__team_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_teams__team_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTeamMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_teams__team_id__members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_role_api_teams__team_id__members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
                member_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamMemberRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_default_team_api_teams__team_id__set_default_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_tickets_get: {
        parameters: {
            query?: {
                sort_by?: string;
                sort_dir?: string;
                page?: number;
                page_size?: number;
                team_id?: number | null;
                owner_id?: number | null;
                support_assignee_id?: number | null;
                category_id?: number | null;
                priority?: components["schemas"]["TicketPriority"] | null;
                status?: components["schemas"]["TicketStatus"] | null;
                sla_status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket_api_tickets_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_ticket_api_tickets__ticket_id__assign_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-email"?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_ticket_priority_api_tickets__ticket_id__priority_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-email"?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriorityChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_ticket_api_tickets__ticket_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-email"?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_ticket_status_api_tickets__ticket_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-email"?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ticket_tags_api_tickets__ticket_id__tags_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-email"?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_ticket_team_api_tickets__ticket_id__team_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-email"?: string | null;
            };
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_timeline_api_tickets__ticket_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    slack_events_slack_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
