"""add fixed business_id mobile_number doctor_name fields

Revision ID: 2111ff92278c
Revises: b0af11f2146d
Create Date: 2026-09-22 15:46:53.081232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2111ff92278c'
down_revision = 'b0af11f2146d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('business_id', sa.String(length=100), nullable=True))
    op.add_column('tickets', sa.Column('mobile_number', sa.String(length=32), nullable=True))
    op.add_column('tickets', sa.Column('doctor_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'doctor_name')
    op.drop_column('tickets', 'mobile_number')
    op.drop_column('tickets', 'business_id')
    # ### end Alembic commands ###
