"""add custom fields and archive flags

Revision ID: 60db42318068
Revises: a86c3ec9d8c2
Create Date: 2026-09-20 10:07:20.984701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60db42318068'
down_revision = 'a86c3ec9d8c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'DROPDOWN', name='custom_field_type'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['custom_field_definitions.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'field_definition_id', name='uq_ticket_custom_field')
    )
    op.create_index(op.f('ix_ticket_custom_field_values_ticket_id'), 'ticket_custom_field_values', ['ticket_id'], unique=False)
    op.add_column('categories', sa.Column('is_archived', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('sla_policies', sa.Column('is_archived', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sla_policies', 'is_archived')
    op.drop_column('categories', 'is_archived')
    op.drop_index(op.f('ix_ticket_custom_field_values_ticket_id'), table_name='ticket_custom_field_values')
    op.drop_table('ticket_custom_field_values')
    op.drop_table('custom_field_definitions')
    # ### end Alembic commands ###
