"""replace sla policies with a single global sla setting

Revision ID: 8943e55243a4
Revises: d495b06a1416
Create Date: 2026-09-23 18:36:15.638142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8943e55243a4'
down_revision = 'd495b06a1416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('sla_hours', sa.Integer(), server_default='48', nullable=False))
    op.drop_constraint('tickets_sla_policy_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'sla_policy_id')
    op.drop_table('sla_policies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_policies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('duration_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='sla_priority'), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='sla_policies_category_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='sla_policies_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sla_policies_pkey')
    )
    op.add_column('tickets', sa.Column('sla_policy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute("INSERT INTO sla_policies (name, duration_hours, is_default, is_archived, created_at) VALUES ('48 hours', 48, true, false, now())")
    op.execute("UPDATE tickets SET sla_policy_id = (SELECT id FROM sla_policies LIMIT 1)")
    op.alter_column('tickets', 'sla_policy_id', nullable=False)
    op.create_foreign_key('tickets_sla_policy_id_fkey', 'tickets', 'sla_policies', ['sla_policy_id'], ['id'])
    op.drop_column('tickets', 'sla_hours')
    op.drop_table('sla_settings')
    # ### end Alembic commands ###
