"""add roles table and team member role fk

Revision ID: a86c3ec9d8c2
Revises: ac96a6a26e96
Create Date: 2026-09-20 09:36:29.947161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a86c3ec9d8c2'
down_revision = 'ac96a6a26e96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('can_create_settings', sa.Boolean(), nullable=False),
    sa.Column('can_edit_settings', sa.Boolean(), nullable=False),
    sa.Column('can_delete_settings', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('team_members', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team_members', 'roles', ['role_id'], ['id'])
    op.drop_column('team_members', 'role')
    # Role is now an admin-managed table, not a fixed enum — drop the type
    # left behind by the dropped column (Alembic doesn't do this itself).
    op.execute("DROP TYPE IF EXISTS team_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE team_role AS ENUM ('MEMBER', 'MANAGER')")
    op.add_column('team_members', sa.Column('role', postgresql.ENUM('MEMBER', 'MANAGER', name='team_role', create_type=False), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
