"""add team routing, support assignee lock, team history

Revision ID: d495b06a1416
Revises: 2111ff92278c
Create Date: 2026-09-22 16:29:14.868449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd495b06a1416'
down_revision = '2111ff92278c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_team_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('previous_team_id', sa.Integer(), nullable=True),
    sa.Column('new_team_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['previous_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_team_history_ticket_id'), 'ticket_team_history', ['ticket_id'], unique=False)
    op.add_column('teams', sa.Column('is_default', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('ticket_assignments', 'new_owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tickets', sa.Column('support_assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['support_assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'support_assignee_id')
    op.alter_column('ticket_assignments', 'new_owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('teams', 'is_default')
    op.drop_index(op.f('ix_ticket_team_history_ticket_id'), table_name='ticket_team_history')
    op.drop_table('ticket_team_history')
    # ### end Alembic commands ###
